apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: app
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_DB
              value: linksdb
