apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener-frontend
  template:
    metadata:
      labels:
        app: shortener-frontend
    spec:
      containers:
        - name: shortener-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80