apiVersion: v1
kind: Service
metadata:
  name: shortener-db-svc
  namespace: shortener
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: db
  selector:
    app: database